import json
from pathlib import Path

import joblib
import pandas as pd
import streamlit as st


# Page configuration - Keep the application focused on operational decision support
st.set_page_config(
    page_title="DataCo Supply Chain Risk Predictor",
    page_icon="",
    layout="wide",
)

BASE_DIR = Path(__file__).resolve().parent

MODEL_PATH = BASE_DIR / "supply_chain_model.pkl"
FEATURES_PATH = BASE_DIR / "model_features.pkl"
METRICS_PATH = BASE_DIR / "model_metrics.json"
CONFIG_PATH = BASE_DIR / "business_config.json"


EXPECTED_FEATURES = [
    "Type",
    "Days for shipment (scheduled)",
    "Shipping Mode",
    "Order Item Quantity",
    "Sales",
    "Order Item Discount",
    "Category Name",
    "Department Name",
    "Order Region",
]

# These are retrospective business-analysis statistics, not prediction rules.
HISTORICAL_SHIPPING_RISK = {
    "First Class": 95.32,
    "Standard Class": 38.07,
}


@st.cache_resource
def load_model():
    """Load the complete trained preprocessing + model pipeline once per session."""
    return joblib.load(MODEL_PATH)


@st.cache_data
def load_json(path):
    """Load deployment configuration and model evaluation results."""
    with open(path, "r", encoding="utf-8") as file:
        return json.load(file)


def get_model_features(feature_object):
    """Read the saved feature schema from the final notebook artifact."""
    if isinstance(feature_object, dict):
        return feature_object["features"]
    return feature_object


def get_category_options(model_pipeline, column_name):
    """Read categorical values from the fitted encoder inside the saved pipeline."""
    preprocessor = model_pipeline.named_steps["preprocessor"]
    encoder = preprocessor.named_transformers_["categorical"]
    categorical_columns = list(preprocessor.transformers[0][2])
    index = categorical_columns.index(column_name)
    return list(encoder.categories_[index])


def classify_risk(probability):
    """Apply transparent presentation-level risk bands to model probability."""
    if probability >= 0.70:
        return "High Risk", "Prioritize intervention before shipment execution."
    if probability >= 0.40:
        return "Medium Risk", "Review the order for proactive monitoring."
    return "Low Risk", "Standard monitoring is appropriate."


# Validate the deployment handoff before rendering the prediction interface.
required_files = [
    MODEL_PATH,
    FEATURES_PATH,
    METRICS_PATH,
    CONFIG_PATH,
]

missing_files = [path.name for path in required_files if not path.exists()]

if missing_files:
    st.error(
        "Required deployment artifacts are missing: "
        + ", ".join(missing_files)
    )
    st.stop()

try:
    model = load_model()
    feature_object = joblib.load(FEATURES_PATH)
    metrics = load_json(METRICS_PATH)
    business_config = load_json(CONFIG_PATH)
except Exception as exc:
    st.error(f"Unable to load the production artifacts: {exc}")
    st.stop()

feature_cols = get_model_features(feature_object)

if feature_cols != EXPECTED_FEATURES:
    st.error(
        "Model feature schema does not match the validated training schema."
    )
    st.stop()


# Minimal styling - Improve hierarchy without adding decorative complexity.
st.markdown(
    """
    <style>
        .block-container {
            padding-top: 2rem;
            padding-bottom: 2rem;
        }

        .risk-note {
            padding: 0.75rem 1rem;
            border-radius: 0.35rem;
            background: #f6f7f9;
            border: 1px solid #e1e4e8;
            font-size: 0.90rem;
        }

        .section-note {
            color: #5f6368;
            font-size: 0.88rem;
        }
    </style>
    """,
    unsafe_allow_html=True,
)


st.title("DataCo Supply Chain Late-Delivery Risk Predictor")
st.caption(
    "Production demonstration using the same trained preprocessing + Gradient Boosting "
    "pipeline generated by the final analytics notebook."
)

st.info(
    "Prediction point: order placement. Post-shipment outcome fields such as actual "
    "shipping duration are intentionally excluded from the model input."
)


with st.sidebar:
    st.subheader("Model Validation")

    metric_col1, metric_col2 = st.columns(2)
    with metric_col1:
        st.metric("Accuracy", f"{metrics['accuracy']:.1%}")
        st.metric("Recall", f"{metrics['recall']:.1%}")
        st.metric("ROC-AUC", f"{metrics['roc_auc']:.1%}")

    with metric_col2:
        st.metric("Precision", f"{metrics['precision']:.1%}")
        st.metric("F1 Score", f"{metrics['f1_score']:.1%}")
        st.metric("CV Accuracy", f"{metrics['cross_validation_accuracy']:.1%}")

    st.caption(
        "Current holdout/CV results from the executed notebook; "
        "not a guarantee of production performance."
    )

    st.subheader("Risk Bands")
    st.write("Low Risk: < 40%")
    st.write("Medium Risk: 40%–69.9%")
    st.write("High Risk: ≥ 70%")

    st.subheader("Scenario Assumptions")
    st.write(
        f"Late-delivery penalty: "
        f"${business_config['late_delivery_penalty']:,.2f}"
    )
    st.write(
        f"Expedite cost: "
        f"${business_config['expedite_cost']:,.2f}"
    )
    st.caption(
        "Financial values are assumption-based scenario inputs, not realized savings."
    )


type_options = get_category_options(model, "Type")
shipping_options = get_category_options(model, "Shipping Mode")
category_options = get_category_options(model, "Category Name")
department_options = get_category_options(model, "Department Name")
region_options = get_category_options(model, "Order Region")


st.subheader("Order Inputs")

with st.form("prediction_form"):
    col1, col2, col3 = st.columns(3)

    with col1:
        transaction_type = st.selectbox(
            "Transaction Type",
            type_options,
            index=0,
        )

        scheduled_days = st.number_input(
            "Days for Shipment (Scheduled)",
            min_value=0,
            max_value=30,
            value=3,
            step=1,
        )

        shipping_mode = st.selectbox(
            "Shipping Mode",
            shipping_options,
            index=shipping_options.index("Standard Class"),
        )

    with col2:
        quantity = st.number_input(
            "Order Item Quantity",
            min_value=1,
            max_value=100,
            value=1,
            step=1,
        )

        sales = st.number_input(
            "Sales",
            min_value=0.0,
            max_value=100000.0,
            value=100.0,
            step=10.0,
        )

        discount = st.number_input(
            "Order Item Discount",
            min_value=0.0,
            max_value=10000.0,
            value=0.0,
            step=1.0,
        )

    with col3:
        category = st.selectbox(
            "Category Name",
            category_options,
            index=category_options.index("Fishing"),
        )

        department = st.selectbox(
            "Department Name",
            department_options,
            index=department_options.index("Outdoors"),
        )

        region = st.selectbox(
            "Order Region",
            region_options,
            index=region_options.index("South Asia"),
        )

    submitted = st.form_submit_button(
        "Predict Late-Delivery Risk",
        use_container_width=True,
    )


if submitted:
    input_data = pd.DataFrame(
        [
            {
                "Type": transaction_type,
                "Days for shipment (scheduled)": scheduled_days,
                "Shipping Mode": shipping_mode,
                "Order Item Quantity": quantity,
                "Sales": sales,
                "Order Item Discount": discount,
                "Category Name": category,
                "Department Name": department,
                "Order Region": region,
            }
        ],
        columns=feature_cols,
    )

    try:
        prediction = int(model.predict(input_data)[0])
        probability = float(model.predict_proba(input_data)[0, 1])
    except Exception as exc:
        st.error(f"Prediction failed: {exc}")
        st.stop()

    risk_label, recommendation = classify_risk(probability)

    st.divider()
    st.subheader("Prediction Result")

    result_col1, result_col2, result_col3 = st.columns(3)

    with result_col1:
        st.metric(
            "Late-Delivery Probability",
            f"{probability:.1%}",
        )

    with result_col2:
        st.metric(
            "Model Classification",
            "Late Delivery" if prediction == 1 else "Not Late",
        )

    with result_col3:
        st.metric(
            "Business Risk Band",
            risk_label,
        )

    st.markdown(
        f"""
        <div class="risk-note">
            <strong>Probability-based risk band:</strong>
            {risk_label}. The band is derived from the model probability and does not
            use shipping mode as a hard-coded prediction rule.
        </div>
        """,
        unsafe_allow_html=True,
    )

    if prediction == 1:
        st.warning(
            f"Predicted late-delivery probability is {probability:.1%}. "
            "Proactive operational review is recommended."
        )
    else:
        st.success(
            f"Predicted late-delivery probability is {probability:.1%}. "
            "The model does not classify this order as late."
        )

    if shipping_mode in HISTORICAL_SHIPPING_RISK:
        historical_rate = HISTORICAL_SHIPPING_RISK[shipping_mode]
        st.caption(
            f"Historical context: {shipping_mode} had an observed late-delivery "
            f"rate of approximately {historical_rate:.2f}% in the analyzed dataset. "
            "This retrospective statistic does not drive the ML prediction."
        )

    st.subheader("Recommended Action")
    st.write(recommendation)

    st.subheader("Financial Impact Context")

    penalty = float(business_config["late_delivery_penalty"])
    expedite = float(business_config["expedite_cost"])
    expected_exposure = probability * penalty

    impact_col1, impact_col2, impact_col3 = st.columns(3)

    with impact_col1:
        st.metric(
            "Expected Late-Delivery Exposure",
            f"${expected_exposure:,.2f}",
        )

    with impact_col2:
        st.metric(
            "Scenario Late Cost",
            f"${penalty:,.2f}",
        )

    with impact_col3:
        st.metric(
            "Scenario Expedite Cost",
            f"${expedite:,.2f}",
        )

    st.caption(
        "Expected exposure is a probability-weighted scenario calculation. "
        "It is not realized savings and is separate from the notebook's "
        "test-cohort ROI scenario."
    )

    with st.expander("Model Input Audit"):
        st.dataframe(
            input_data,
            use_container_width=True,
            hide_index=True,
        )

        st.write(
            "The application passes the input DataFrame directly to the saved "
            "pipeline. Categorical encoding and numeric preprocessing are handled "
            "inside the trained pipeline."
        )

st.divider()
st.caption(
    "DataCo Supply Chain Analytics | Leakage-controlled predictive analytics demonstration"
)
